In [1]:
%load_ext autoreload
%autoreload 2
from get_pageviews import *

In [2]:
d1 = get_month_pageviews_pre_hive()

In [3]:
d1.head()

           access_method country_iso        n       project   timestamp
timestamp
2013-04-01    mobile web          AF   1000.0  de.wikipedia  2013-04-01
2013-04-01       desktop          AF  22000.0  en.wikipedia  2013-04-01
2013-04-01    mobile web          AF   8000.0  en.wikipedia  2013-04-01
2013-04-01       desktop          AF   8000.0  fa.wikipedia  2013-04-01
2013-04-01    mobile web          AF   3000.0  fa.wikipedia  2013-04-01

In [4]:
d2 = get_month_pageviews_post_hive()

In [5]:
df = pd.concat([d1, d2], axis=0)

In [6]:
df.head()

           access_method country_iso        n       project   timestamp
timestamp
2013-04-01    mobile web          AF   1000.0  de.wikipedia  2013-04-01
2013-04-01       desktop          AF  22000.0  en.wikipedia  2013-04-01
2013-04-01    mobile web          AF   8000.0  en.wikipedia  2013-04-01
2013-04-01       desktop          AF   8000.0  fa.wikipedia  2013-04-01
2013-04-01    mobile web          AF   3000.0  fa.wikipedia  2013-04-01

In [7]:
df = replace_iso_with_country(df)

In [8]:
df.tail()

,access_method,country_iso,n,project,timestamp,country
timestamp,,,,,,
2017-02-01,mobile web,ZW,11.0,so.wikipedia,2017-02-01,Zimbabwe
2017-02-01,mobile web,ZW,52.0,st.wikipedia,2017-02-01,Zimbabwe
2017-02-01,mobile web,ZW,2.0,te.wikipedia,2017-02-01,Zimbabwe
2017-02-01,mobile web,ZW,1.0,vec.wikipedia,2017-02-01,Zimbabwe
2017-02-01,desktop,ZW,1.0,yo.wikipedia,2017-02-01,Zimbabwe

In [9]:
df.to_csv('data/checkpoint.csv')

In [10]:
df_cube = untidy(df)

In [11]:
df_cube.head()

,timestamp,ab.wikipedia/desktop/United States,"ace.wikipedia/desktop/China, People's Republic of",ace.wikipedia/desktop/Germany,ace.wikipedia/desktop/United States,af.wikipedia/desktop/Canada,"af.wikipedia/desktop/China, People's Republic of",af.wikipedia/desktop/France,af.wikipedia/desktop/Germany,af.wikipedia/desktop/Netherlands,...,zh.wikipedia/mobile web/Sweden,zh.wikipedia/mobile web/Switzerland,zh.wikipedia/mobile web/Thailand,zh.wikipedia/mobile web/Turkey,zh.wikipedia/mobile web/United Arab Emirates,zh.wikipedia/mobile web/United Kingdom,zh.wikipedia/mobile web/United States,zh.wikipedia/mobile web/Unknown,zh.wikipedia/mobile web/Vietnam,zu.wikipedia/desktop/United States
2013-04-01,2013-04-01,1000.0,NaN,NaN,3000.0,NaN,3000.0,NaN,1000.0,1000.0,...,NaN,NaN,1000.0,NaN,NaN,6000.0,27000.0,31000.0,2000.0,2000.0
2013-05-01,2013-05-01,63000.0,7000.0,11000.0,70000.0,11000.0,108000.0,18000.0,184000.0,30000.0,...,19000.0,16000.0,50000.0,11000.0,3000.0,283000.0,1244000.0,1365000.0,33000.0,15000.0
2013-06-01,2013-06-01,24000.0,6000.0,21000.0,39000.0,6000.0,30000.0,12000.0,152000.0,39000.0,...,20000.0,8000.0,52000.0,14000.0,14000.0,224000.0,1271000.0,1454000.0,36000.0,24000.0
2013-07-01,2013-07-01,31000.0,7000.0,9000.0,54000.0,5000.0,30000.0,11000.0,115000.0,30000.0,...,21000.0,16000.0,71000.0,6000.0,10000.0,265000.0,1493000.0,1597000.0,50000.0,34000.0
2013-08-01,2013-08-01,81000.0,9000.0,9000.0,144000.0,9000.0,42000.0,17000.0,151000.0,15000.0,...,29000.0,15000.0,75000.0,6000.0,10000.0,230000.0,1557000.0,1305000.0,58000.0,63000.0

In [12]:
df_cube.to_csv('data/cube.csv', index = False)